version: '3.8'

services:
  jahitstatus-lp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jahitstatus-lp-dev
    ports:
      - "3200:3200"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0